name: Build Docs
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - release/*

jobs:

  build-docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: x64
      - name: Checkout functorch
        uses: actions/checkout@v2
      - name: Install PyTorch 1.11
        run: |
          python3 -mpip install torch==1.11.0
      - name: Install functorch
        run: |
          python3 setup.py install
      - name: Install docs requirements
        run: |
          cd docs
          python3 -mpip install -r requirements.txt
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Upload docs as GHA artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs.whl
          path: docs/build/html
